spring:
  main:
    log-startup-info: false
    banner-mode: off
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shares_db
    username: sa
    password: password
    driverClassName: org.postgresql.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: trace