server:
  port: 9090
spring:
  main:
    log-startup-info: false
    banner-mode: off
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: dbuser
    password: 12345
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
logging.level.org:
  zalando:
    logbook: INFO