CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP                                 NOT NULL,
    end_date   TIMESTAMP                                 NOT NULL,
    item_id    BIGINT                                    NOT NULL,
    booker_id  BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
    status     VARCHAR                                   NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR                                   NOT NULL,
    requestor_id BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
    created      TIMESTAMP                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR                                   NOT NULL,
    description  VARCHAR                                   NOT NULL,
    is_available BOOLEAN                                   NOT NULL,
    owner_id     BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
    request_id   BIGINT REFERENCES requests ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR                                   NOT NULL,
    item_id   BIGINT REFERENCES items ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users ON DELETE CASCADE NOT NULL,
    created   TIMESTAMP                                 NOT NULL
);